server:
  port: 9000
spring:
  profiles:
    active:
      - qa
  config:
    import:
      - application_qa.yml
      - application_prod.yml
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdbcards
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: 3.0

cards:
  message: Welcome to the Cards Service!
  contactDetails:
    name: Cards Service
    email: support@cards.com
  onCallSupport:
    - +1-800-123-4567
    - +1-800-987-6543