server:
  port: 9000
spring:
  application:
    name: cards
  config:
    import:
      - "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - qa
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bank
    password: bank
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"