spring:
  config:
    activate:
      on-profile: prod

build:
  version: 1.0

cards:
  message: Welcome to the Cards Service related to Production APIs!
  contactDetails:
    name: Cards Service
    email: support@cards.com
  onCallSupport:
    - +1-800-123-4567
    - +1-800-987-6543