server:
  port: 8090
spring:
  profiles:
    active:
      - qa
  config:
    import:
      - application_qa.yml
      - application_prod.yml
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdbloans
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

build:
  version: 3.0

loans:
  message: Welcome to the Loans Service!
  contactDetails:
    name: Loans Service
    email: support@loans.com
  onCallSupport:
    - +1-800-123-4567
    - +1-800-987-6543