server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdbaccounts
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

build:
  version: 1.0