server:
  port: 8071
spring:
  application:
    name: configserver
  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YanVelasco/bank-config
          username: yanvelasco
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"