build:
  version: 2.0

cards:
  message: Welcome to the Cards Service related to QA APIs!
  contactDetails:
    name: Cards Service
    email: support@cards.com
  onCallSupport:
    - +1-800-123-4567
    - +1-800-987-6543