build:
  version: 2.0

loans:
  message: Welcome to the Loans Service related to QA APIs!
  contactDetails:
    name: Loans Service
    email: support@loans.com
  onCallSupport:
    - +1-800-123-4567
    - +1-800-987-6543